<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Categorical-Feature-Engineering-" data-toc-modified-id="Categorical-Feature-Engineering--1">Categorical Feature Engineering </a></span></li><li><span><a href="#Learning-Outcomes" data-toc-modified-id="Learning-Outcomes-2">Learning Outcomes</a></span></li><li><span><a href="#Categorical-Feature-Engineering-" data-toc-modified-id="Categorical-Feature-Engineering--3">Categorical Feature Engineering </a></span></li><li><span><a href="#What-are-the-methods-to-encode-categorical-features?" data-toc-modified-id="What-are-the-methods-to-encode-categorical-features?-4">What are the methods to encode categorical features?</a></span></li><li><span><a href="#What-is-the-difference-between-pd.get_dummies-and-sklearn.preprocessing.OneHotEncoder?" data-toc-modified-id="What-is-the-difference-between-pd.get_dummies-and-sklearn.preprocessing.OneHotEncoder?-5">What is the difference between pd.get_dummies and sklearn.preprocessing.OneHotEncoder?</a></span></li><li><span><a href="#What-is-Hashing?" data-toc-modified-id="What-is-Hashing?-6">What is Hashing?</a></span></li><li><span><a href="#What-are-Hash-Maps?" data-toc-modified-id="What-are-Hash-Maps?-7">What are Hash Maps?</a></span></li><li><span><a href="#Feature-Hashing,-aka-hashing-trick" data-toc-modified-id="Feature-Hashing,-aka-hashing-trick-8">Feature Hashing, aka hashing trick</a></span></li><li><span><a href="#The-Advantages-of-Feature-Hashing" data-toc-modified-id="The-Advantages-of-Feature-Hashing-9">The Advantages of Feature Hashing</a></span></li><li><span><a href="#The-Disadvantages-of-Feature-Hashing" data-toc-modified-id="The-Disadvantages-of-Feature-Hashing-10">The Disadvantages of Feature Hashing</a></span></li><li><span><a href="#Embeddings-(e.g.,-word2vec)" data-toc-modified-id="Embeddings-(e.g.,-word2vec)-11">Embeddings (e.g., word2vec)</a></span></li><li><span><a href="#How-to-use-word-embeddings-in-a-ML-Algorithm" data-toc-modified-id="How-to-use-word-embeddings-in-a-ML-Algorithm-12">How to use word embeddings in a ML Algorithm</a></span></li><li><span><a href="#StarSpace-Package:-Embed-All-The-Things!" data-toc-modified-id="StarSpace-Package:-Embed-All-The-Things!-13">StarSpace Package: Embed All The Things!</a></span></li><li><span><a href="#How-to-use-StarSpace-embeddings-in-a-ML-Algorithm" data-toc-modified-id="How-to-use-StarSpace-embeddings-in-a-ML-Algorithm-14">How to use StarSpace embeddings in a ML Algorithm</a></span></li><li><span><a href="#Comparing-Encoding-Methods" data-toc-modified-id="Comparing-Encoding-Methods-15">Comparing Encoding Methods</a></span></li><li><span><a href="#Takeaways" data-toc-modified-id="Takeaways-16">Takeaways</a></span></li><li><span><a href="#Bonus-Material" data-toc-modified-id="Bonus-Material-17">Bonus Material</a></span></li><li><span><a href="#Bin-Counting" data-toc-modified-id="Bin-Counting-18">Bin Counting</a></span></li><li><span><a href="#Bin-Counting" data-toc-modified-id="Bin-Counting-19">Bin Counting</a></span></li><li><span><a href="#Check-for-understanding" data-toc-modified-id="Check-for-understanding-20">Check for understanding</a></span></li></ul></div>

<center><h2>Categorical Feature Engineering </h2></center>

<center><img src="images/0_iKsDex5fUBQoYTju.png" width="100%"/></center>

<center><h2>Learning Outcomes</h2></center>

__By the end of this session, you should be able to__:

- List the common methods of encoding categorical features.
- Compare and contrast the common methods of encoding categorical features.

<center><h2>Categorical Feature Engineering </h2></center>

Categorical variables needs to be transformed into numbers that amendable to machine learning.

Examples of categorical variables: Products, users, words, …

<center><h2>What are the methods to encode categorical features?</h2></center>

- One-Hot Encoding / Dummy Encoding
- Label Encoding
- Feature Hashing
- Embeddings 

<center><h2>What is the difference between pd.get_dummies and sklearn.preprocessing.OneHotEncoder?</h2></center>

`pd.get_dummies` creates a DataFrame to manage encoded variables.

`sklearn.preprocessing.OneHotEncoder` creates an OneHotEncoder object to manage encoded variables.

In [1]:
reset -fs

In [10]:
import numpy as np

X = np.array(['Positive', 'Positive', 'Negative'])

In [3]:
import pandas as pd

pd.get_dummies(pd.Series(X))

Negative  Positive
0         0         1
1         0         1
2         1         0

In [4]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
enc.fit(X.reshape(-1, 1))
enc.get_feature_names()

array(['x0_Negative', 'x0_Positive'], dtype=object)

In [5]:
enc.transform(X.reshape(-1, 1)).toarray()

array([[0., 1.],
       [0., 1.],
       [1., 0.]])

In [6]:
# Combine fit and transform
enc.fit_transform(X.reshape(-1, 1)).toarray()

array([[0., 1.],
       [0., 1.],
       [1., 0.]])

<center><h2>What is Hashing?</h2></center>

<center>Converting an object into a single numeric value.</center>

<center> Map data of arbitrary sizes to data of a fixed size.</center>

<center><h2>What are Hash Maps?</h2></center>

<center>Key-value pairs - where the key is numeric location (index) and the value is an object</center>

<center><h2>Feature Hashing, aka hashing trick</h2></center>
<br>
<center><img src="images/feature_hashing.jpeg" width="100%"/></center>

<center>Map feature values to indices in a feature vector.</center>

<center>Those feature values could be <b>any</b> hashable object</center>

Source: https://www.quora.com/Can-you-explain-feature-hashing-in-an-easily-understandable-way

In [11]:
from sklearn.feature_extraction import FeatureHasher

FeatureHasher?

In [16]:
# Let's feature hash 
h = FeatureHasher(n_features=10)
# d = [{'dog': 10,}] # 1 instance & 1 feature with a value
# d = [{'dog': 4,}] # 1 instance & 1 feature with a changed value
# d = [{'dog': 10, 'cat':2, 'elephant':4}] # 1 instance & 3 features
# d = [{'dog': 10, 'cat':2, 'elephant':4}, # 2 instances
#      {'dog': 2, 'run': 5}] 
d = [{l:n for l, n in zip('abcdefghijklmnopqrstuvwxyz', range(26))}] # 1 instance & many features 🤭
    
h.transform(d).toarray()

array([[-16., -50.,  25.,  21.,  11., -15.,  -3.,  -2.,   0., -30.]])

Learn more: https://www.youtube.com/watch?v=Uv9dY6Obv-s

<center><h2>The Advantages of Feature Hashing</h2></center>

- Fast 
- Simple
- Memory efficient
    - Limits feature vector size (compared to one-hot encoding)
    - No need to store mapping feature itself (just index integer)

<center><h2>The Disadvantages of Feature Hashing</h2></center>

- Interpretability & feature importances - Cannot go from feature indices back to feature names
- Hash collisions 

<center><h2>Embeddings (e.g., word2vec)</h2></center>

<center><img src="images/0_A9qy9wS7m-eMKiX6.png" width="45%"/></center>

<center>Project sparse high-dimensional categorical data into a dense, low-dimensional numeric vector.</center>

Source: https://instagram-engineering.com/emojineering-part-1-machine-learning-for-emoji-trendsmachine-learning-for-emoji-trends-7f5f9cb979ad

<center><h2>How to use word embeddings in a ML Algorithm</h2></center>

1. Train (or download) word embeddings.
1. Create a document embedding by taking the an average of words vectors for that document.
1. Each dimension is a feature.
1. Train the machine learning algorithm.

For example, tree-based classifier would learn which parts of the embedding space are associated with a specific label.

<center><h2>StarSpace Package: Embed All The Things!</h2></center>

<center><img src="images/product_embedding.png" width="75%"/></center>

Embedded any sequential discrete data. 

Examples: Words, emojis, documents, products, images, videos, …

<center><h2>How to use StarSpace embeddings in a ML Algorithm</h2></center>

1. Train (or download) embeddings where every entity is embedded into the same space.
1. Each dimension is a feature.
1. Train the machine learning algorithm.

Source: 

- https://research.fb.com/downloads/starspace/
- https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/viewPaper/16998

In [9]:
%%HTML
<style>
.rendered_html table, .rendered_html th, .rendered_html tr, .rendered_html td {
     font-size: 100%;
}
</style>

<center><h2>Comparing Encoding Methods</h2></center>

| Method | Size Requirements |  Growth |
|:-------:|:------:|:------:|
| One-Hot Encoding | Cardinality of data| Unbounded |
| Feature Hashing | Hash table size | Fixed | 
| Embeddings | Feature space dimensions | Fixed | 

<center><h2>Takeaways</h2></center>

- One-hot encoding works well for small number of categories
- Features hashing works well for medium number of categories.
- Embeddings are the best choice (if possible).


Bonus Material
-----

Bin Counting
-------

<center><img src="images/counts.png" width="75%"/></center>

Rather than using the value of the categorical variable as the feature, instead use the __conditional probability of the target under that value__.

Bin Counting
-----

<center><img src="images/bin_conts.png" width="75%"/></center>

Use probability of click as a feature (not just raw click or not click).

Turns a large, sparse, binary representation of the categorical variable (e.g., one-hot encoding) into a very small, dense, real-valued numeric representation

Bin Counting: _m_ bin table size, fixed

Check for understanding
-----

What is the difference between Bin Counting and Naive Bayes?

Naive Bayes always multiplies the conditional probabilities.

Bin counting treat them as features, which can be used in other models such as trees.

Learn more:
- https://blogs.technet.microsoft.com/machinelearning/2015/02/17/big-learning-made-easy-with-counts/
- https://www.slideshare.net/SessionsEvents/misha-bilenko-principal-researcher-microsoft

<br>